name: CI

on: "push"

jobs:
  formatting:
    name: Formatting
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - run: cargo fmt --check

  test:
    name: Test
    runs-on: ubuntu-latest
    needs: "formatting"
    strategy:
      matrix:
        toolchain: ["stable", "beta", "nightly"]

    steps:
      - uses: actions/checkout@v3
      - run: cargo build --verbose
      - run: cargo test --verbose
